<Project>
  <PropertyGroup>
    <VersionMajor>0</VersionMajor>
    <VersionMinor>9</VersionMinor>
    <VersionPatch>9</VersionPatch>
    <VersionPrefix>$(VersionMajor).$(VersionMinor).$(VersionPatch)</VersionPrefix>
    <Version Condition="'$(VersionSuffix)' == ''">$(VersionPrefix)</Version>
    <Version Condition="'$(VersionSuffix)' != ''">$(VersionPrefix)-$(VersionSuffix)</Version>
    <AssemblyVersion>$(VersionMajor).$(VersionMinor).0.0</AssemblyVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
